include:
  - ./services/traefik/docker-compose.yml
  - ./services/gluetun/docker-compose.yml
  - ./services/qbittorrent/docker-compose.yml
  - ./services/prowlarr/docker-compose.yml
  - ./services/radarr/docker-compose.yml
  - ./services/sonarr/docker-compose.yml
  - ./services/jellyfin/docker-compose.yml
  - ./services/homarr/docker-compose.yml
  - ./services/uptime-kuma/docker-compose.yml
  - ./services/beszel/docker-compose.yml
  - ./services/immich/docker-compose.yml
  - ./services/n8n/docker-compose.yml

networks:
  homelab:
    name: homelab
    external: false
