EXERCISE_TYPES: dict[int, str] = {
    0: "Unknown",
    1: "Badminton",
    2: "Baseball",
    3: "Basketball",
    4: "Biking",
    5: "Biking (stationary)",
    6: "Boot camp",
    7: "Boxing",
    8: "Calisthenics",
    9: "Cricket",
    10: "Dancing",
    11: "Exercise class",
    12: "Fencing",
    13: "Football (American)",
    14: "Football (Australian)",
    15: "Frisbee",
    16: "Golf",
    17: "Guided breathing",
    18: "Gymnastics",
    19: "Handball",
    20: "HIIT",
    21: "Hiking",
    22: "Ice hockey",
    23: "Ice skating",
    24: "Martial arts",
    25: "Paddling",
    26: "Paragliding",
    27: "Pilates",
    28: "Racquetball",
    29: "Rock climbing",
    30: "Roller hockey",
    31: "Rowing",
    32: "Rugby",
    33: "Running",
    34: "Running (treadmill)",
    35: "Sailing",
    36: "Scuba diving",
    37: "Skating",
    38: "Skiing",
    39: "Snowboarding",
    40: "Snowshoeing",
    41: "Soccer",
    42: "Softball",
    43: "Squash",
    44: "Stair climbing",
    45: "Strength training",
    46: "Stretching",
    47: "Surfing",
    48: "Swimming (open water)",
    49: "Swimming (pool)",
    50: "Table tennis",
    51: "Tennis",
    52: "Volleyball",
    53: "Walking",
    54: "Water polo",
    55: "Weightlifting",
    56: "Wheelchair",
    57: "Yoga",
    58: "Other workout",
    59: "Stair climbing (machine)",
    60: "Elliptical",
    61: "Rowing (machine)",
}

SLEEP_STAGES: dict[int, str] = {
    1: "awake",
    2: "sleeping",
    3: "out_of_bed",
    4: "light",
    5: "deep",
    6: "rem",
}

CALORIES_TO_KCAL = 1000.0
GRAMS_TO_KG = 1000.0
METERS_TO_KM = 1000.0
