services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.19
    container_name: homelab-sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ../../data/sonarr:/config
      - ../../data/media/tv:/tv
      - ../../data/media/downloads:/downloads
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN_BASE}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
